# This workflow will move the 'latest' tag when a release is created

name: Create or move the latest tag

on:
  release:
    types:
#      - published
      - created
#      - edited
#      - prereleased
#      - released

permissions:
  contents: write

jobs:
  tag-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: cardinalby/git-tag-action@master
        env:
          TAG: latest
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
